name: base
channels:
  - anaconda
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.12
  - anaconda=2020.02
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.12
  - anaconda-project=0.8.4
  - argh=0.26.2
  - asn1crypto=1.3.0
  - astroid=2.3.3
  - astropy=4.0
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - autopep8=1.4.4
  - babel=2.8.0
  - backcall=0.1.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.1.7
  - beautifulsoup4=4.8.2
  - bitarray=1.2.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.16.3
  - bokeh=1.4.0
  - boto=2.49.0
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.3.0
  - clyent=1.2.2
  - colorama=0.4.3
  - comtypes=1.1.7
  - conda=4.8.3
  - conda-build=3.18.11
  - conda-env=2.6.0
  - conda-package-handling=1.6.1
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - contextlib2=0.6.0.post1
  - cryptography=2.8
  - curl=7.68.0
  - cycler=0.10.0
  - cython=0.29.15
  - cytoolz=0.10.1
  - dask=2.11.0
  - dask-core=2.11.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - diff-match-patch=20181111
  - distributed=2.11.0
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - fastcache=1.1.0
  - filelock=3.0.12
  - flake8=3.7.9
  - flask=1.1.1
  - freetype=2.9.1
  - fsspec=0.6.2
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=1.4.0
  - glob2=0.7
  - greenlet=0.4.15
  - h5py=2.10.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.0.1
  - hypothesis=5.5.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.8
  - imageio=2.6.1
  - imagesize=1.2.0
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - intervaltree=3.0.2
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.14.1
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - json5=0.9.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - keyring=21.1.0
  - kiwisolver=1.1.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - libarchive=3.3.3
  - libcurl=7.68.0
  - libiconv=1.15
  - liblief=0.9.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libspatialindex=1.9.3
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvmlite=0.31.0
  - locket=0.2.0
  - lxml=4.5.0
  - lz4-c=1.8.1.2
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - menuinst=1.4.16
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=4.0.1
  - more-itertools=8.2.0
  - mpmath=1.1.0
  - msgpack-python=0.6.1
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - networkx=2.4
  - nltk=3.4.5
  - nose=1.3.7
  - notebook=6.0.3
  - numba=0.48.0
  - numexpr=2.7.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - numpydoc=0.9.2
  - olefile=0.46
  - openpyxl=3.0.3
  - openssl=1.1.1d
  - packaging=20.1
  - pandas=1.0.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - paramiko=2.7.1
  - parso=0.5.2
  - partd=1.1.0
  - path=13.1.0
  - path.py=12.4.0
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - ply=3.11
  - powershell_shortcut=0.0.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - psutil=5.6.7
  - py=1.8.1
  - py-lief=0.9.0
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.5
  - pydocstyle=4.0.1
  - pyflakes=2.1.1
  - pygments=2.5.2
  - pylint=2.4.4
  - pynacl=1.3.0
  - pyodbc=4.0.30
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=5.3.5
  - pytest-arraydiff=0.3
  - pytest-astropy=0.8.0
  - pytest-astropy-header=0.1.2
  - pytest-doctestplus=0.5.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.7
  - python-libarchive-c=2.8
  - pytz=2019.3
  - pywavelets=1.1.1
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3
  - pyzmq=18.1.1
  - qdarkstyle=2.8
  - qt=5.9.7
  - qtawesome=0.6.1
  - qtconsole=4.6.0
  - qtpy=1.9.0
  - requests=2.22.0
  - rope=0.16.0
  - rtree=0.9.3
  - ruamel_yaml=0.15.87
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=45.2.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.14.0
  - snappy=1.1.7
  - snowballstemmer=2.0.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=1.9.5
  - sphinx=2.4.0
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sphinxcontrib-websupport=1.2.0
  - spyder=4.0.1
  - spyder-kernels=1.8.1
  - sqlalchemy=1.3.13
  - sqlite=3.31.1
  - statsmodels=0.11.0
  - sympy=1.5.1
  - tbb=2020.0
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - ujson=1.35
  - unicodecsv=0.14.1
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - watchdog=0.10.2
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=1.0.0
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - win_unicode_console=0.5
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xlsxwriter=1.2.7
  - xlwings=0.17.1
  - xlwt=1.3.0
  - xmltodict=0.12.0
  - xz=5.2.4
  - yaml=0.1.7
  - yapf=0.28.0
  - zeromq=4.3.1
  - zict=1.0.0
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - arrow==0.15.6
    - astor==0.8.1
    - atari-py==0.2.6
    - binaryornot==0.4.4
    - blis==0.4.1
    - cachetools==4.0.0
    - catalogue==1.0.0
    - cookiecutter==1.7.2
    - cymem==2.0.3
    - docopt==0.6.2
    - en-core-web-md==2.2.5
    - gast==0.2.2
    - glfw==1.11.0
    - google-api-core==1.17.0
    - google-auth==1.11.3
    - google-cloud-bigquery==1.24.0
    - google-cloud-core==1.3.0
    - google-pasta==0.2.0
    - google-resumable-media==0.5.0
    - googleapis-common-protos==1.51.0
    - grpcio==1.27.2
    - gym==0.17.1
    - jinja2-time==0.2.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - lockfile==0.12.2
    - markdown==3.2.1
    - multidict==4.7.5
    - murmurhash==1.0.2
    - opencv-python==4.2.0.34
    - opt-einsum==3.2.0
    - pika==1.1.0
    - pillow==7.1.2
    - plac==1.1.3
    - poyo==0.5.0
    - preshed==3.0.2
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.0
    - pykwalify==1.7.0
    - python-slugify==4.0.0
    - questionary==1.5.1
    - rasa==1.8.2
    - rasa-sdk==1.8.1
    - redis==3.4.1
    - rsa==4.0
    - sanic==19.12.2
    - sanic-cors==0.10.0.post3
    - slackclient==2.5.0
    - spacy==2.2.4
    - srsly==1.0.2
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - text-unidecode==1.3
    - thinc==7.4.0
    - tqdm==4.43.0
    - wasabi==0.6.0
    - word2number==1.1

